### ISSUE TITLE
How to use rigpl-erpnext into the main ERPNext

### ISSUE THREAD

**Issue by stevenyaga** [adityaduggal/rigpl-erpnext#61]
Hi,

I want to use this custom application as part of the ERPNext. I am wondering what configurations i need to make to the main ERPNext to have this custom app visible from the main ERPNext

Regards

**Comment by adityaduggal** [comment]
Hi @stevenyaga 

Please note that rigpl-erpnext is a custom app only for internal use by our organisation and hence its not designed in a way to be installed by other users.

You can easily install the app in your erpnext instance but the problem would be that all the custom fields are not mentioned in the fixtures and hence you would have to create your own custom fields for now.

Also this app only has few validations and some reports. Please do let me know if you have any specific requirements that you think rigpl-erpnext could solve or you are just doing it for learning purpose.
