### ISSUE TITLE
Ability to track all the Various Courier people and their charges

### ISSUE THREAD

**Issue by adityaduggal** [adityaduggal/rigpl-erpnext#69]

**Comment by unmesh87** [comment]
Hi Aditya,

Points for discussion to track courier status in ERPNext system. 

**Goals**-
- Maintain a docket number database, to inform customers about couriered items
- Maintain a docket number database, to verify against purchase invoice sent by courier.

**Notes** - 
**1.** Ordered Item Status
- Not dispatched
- Dispatch
- Ready but not dispatched

****2.** Maintain** Docket Number DocType
- Docket Number
- Courier Transporter
- Supplier Company
- Data from Transporter's Receipt e.g. weight, From to Locations, etc.
- Button to pull details using API (Fedex, Bluedart, DHL)
- Daily or Hourly fire of API request to get status.

**3.** Custom doc_events and script for Purchase Invoice
- Pull "unpaid" dockets from supplier / transporter
- Selection of Dockets. Addition of Dockets into Purchase Invoice item if not found in db

**4.** Custom doc_events and script for Sales Invoice
- Quick entry of Docket
- Validate Docket No. on update_after_submit if transporter has docket_mandatory checkbox

**5.** Transporter DocType
- Transporter Mandatory to have docket no.
- Link Supplier

**6.** Track important letters ERPNext (Potential PR on Communication)

@revant and @gaurav-naik please follow up this post.

**Comment by adityaduggal** [comment]
Please note that I would like to track the dockets generated for specific suppliers. Suppose we are dealing only with Blue Dart (for example) then all the blue dart dockets should be there in the docket doctype.

So dockets can be of many types like:

1. Sending Sales Invoice (material) through courier
1. Sending C-Forms via courier but there is no document in erp to track c-forms so basically we would create a docket document and enter the docket number and then probably in the remarks mention that cform is being sent.
1. Also we send marketing material via courier for which there is no entry in the erp

So like above there are many things which are sent through courier for which we receive and invoice at the end of the month but most of the time the dockets mentioned in the invoice of the courier supplier are not traceable in our system and hence we have no way to verify that the whether the particular docket was sent by us or is it a fake entry in our supplier's invoice.

Also I think we could use this docket doctype to use it as a shipping label printing since this should be having address details in this document so that we could print shipping labels as well, just a thought

**Comment by gaurav-naik** [comment]
1. Dockets can be filtered by Supplier. Can discuss further if this concern has not been adequately addressed.

2. 'Content Type' field on Docket (Select field with Options: Sales Goods, Documents Link Field) to indicate type of goods being transported. Marketing Material, C-Form can be tracked via the Docket doctype where content type = Documents

3. New Purchase Invoice: Items table will be auto-populated with Dockets not already linked to submitted Purchase Invoices.
   
   1. Purchase Invoice Item: Item Name: Can indicate status on entering Docket No in Item Name field - "Already linked to PI #1234" or "No Docket with this no"

Estimated time for implementing Docket doctype and relevant custom fields/scripts + hooks on Purchase Invoice and Sales Invoice doctypes with revisions as per UAT:

**20 hrs**

All customization will be upgrade friendly.

@unmesh will respond with a quotation
