### ISSUE TITLE
Reference Type is Employee Loan

### ISSUE THREAD

**Issue by Helkyd** [adityaduggal/rigpl-erpnext#70]
Where do I enter this as the error giving is that should only be Sales Invoice, Purchase Invoice .....

Using your Erpnext extension to modify the one we have in my country Angola ....
Wonder if I could from time to time ask you for solutions or how did you manage for example to override on the Salary Structure the make_earn_deb with yours ... this because my solution I had to override the file it self so I could make my changes ...

**Comment by adityaduggal** [comment]
@Helkyd you can customize the form view for Journal Voucher Detail and enter the Employee Loan manually into the system
