### ISSUE TITLE
error while installing branch version-12 on erpnext version-12

### ISSUE THREAD

**Issue by Suraj787** [adityaduggal/rigpl-erpnext#73]
error while installing branch version-12 on erpnext version-12

Module import failed for Shipway Settings (rigpl_erpnext.rigpl_erpnext.doctype.shipway_settings.shipway_settings Error: No module named 'fedex')

**Comment by asoral** [comment]
I am also getting the same issue

**Comment by TurkerTunali** [comment]
Issue 

./env/bin/pip install fedex

before install in the bench folder.

**Comment by tufanneo** [comment]
I am also getting the exact same issue, even after running './env/bin/pip install fedex'

**Comment by tufanneo** [comment]
I am getting the following error 'Module import failed for Shipway Settings (rigpl_erpnext.rigpl_erpnext.doctype.shipway_settings.shipway_settings Error: No module named 'rigpl_erpnext.rigpl_erpnext.doctype.carrier_tracking')'
